{"title": "socket.io的 Python客户端中文encode问题 - contiki ", "index": "socket.io,python", "content": "socketIO-client是python实现的SocketIO客户端。\n问题\n当接收到中文消息时出现下方错误，简单说就是编码问题。\nTraceback (most recent call last):\n  File \"sub.py\", line 24, in <module>\n    socketIO.wait()\n  File \"/usr/local/lib/python3.5/site-packages/socketIO_client/__init__.py\", line 232, in wait\n    self._process_packets()\n  File \"/usr/local/lib/python3.5/site-packages/socketIO_client/__init__.py\", line 254, in _process_packets\n    for engineIO_packet in self._transport.recv_packet():\n  File \"/usr/local/lib/python3.5/site-packages/socketIO_client/transports.py\", line 155, in recv_packet\n    six.b(packet_text))\n  File \"/usr/local/lib/python3.5/site-packages/six.py\", line 620, in b\n    return s.encode(\"latin-1\")\nUnicodeEncodeError: 'latin-1' codec can't encode characters in position 21-27: ordinal not in range(256)\n解决方法\n\n找到socketIO_client的安装路径，例中跟six.py在同一目录下，路径是/usr/local/lib/python3.5/site-packages/socketIO_client/.\n找到socketIO_client文件夹下的transports.py文件\n\n用编辑器打开transports.py，在144行左右的位置找到recv_packet函数\ndef recv_packet(self):\n    try:\n        packet_text = self._connection.recv()\n    except websocket.WebSocketTimeoutException as e:\n        raise TimeoutError('recv timed out (%s)' % e)\n    except websocket.SSLError as e:\n        raise ConnectionError('recv disconnected by SSL (%s)' % e)\n    except websocket.WebSocketConnectionClosedException as e:\n        raise ConnectionError('recv disconnected (%s)' % e)\n    except socket.error as e:\n        raise ConnectionError('recv disconnected (%s)' % e)\n    engineIO_packet_type, engineIO_packet_data = parse_packet_text(\n        six.b(packet_text))\n    yield engineIO_packet_type, engineIO_packet_data\n\n修改倒数第二行six.b(packet_text))为six.u(packet_text))，修改后保存.\n再次运行代码接收中文消息，代码正常运行.\n\n\n                ", "mainLikeNum": ["0 "], "mainBookmarkNum": "0"}